services:
  db:
    image: mariadb:10.6 
    container_name: db_mariadb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 12345678 
      MYSQL_DATABASE: crud_db 
      MYSQL_USER: aquarise 
      MYSQL_PASSWORD: 12345678 
    volumes:
      - mariadb_data:/var/lib/mysql 
    networks:
      - app-network

  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: uts-web-app 
    container_name: web_apache
    restart: unless-stopped
    volumes:
      - ./website:/var/www/html
    ports:
      - "8000:80"
    depends_on:
      - db
    networks:
      - app-network

  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime_kuma
    restart: unless-stopped
    volumes:
      - uptime_kuma_data:/app/data
    ports:
      - "3001:3001" 
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mariadb_data:
    driver: local
  uptime_kuma_data:
    driver: local
